name: golang-ci
on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/golangci.yml

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubunt-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - deadcode
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
